# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bNO71z4Qu6j-tE7pqDGYTmIpuwDP5rr8
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
import kagglehub

# Download latest version
path = kagglehub.dataset_download("benjamingray44/inertial-data-for-dog-behaviour-classification")

print("Path to dataset files:", path)

for dirname, _, filenames in os.walk(path):
    for filename in filenames:
        print(os.path.join(dirname, filename))

#imports
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#loading the data, shuffling it, and choosing 200000 instances
movedata = pd.read_csv(os.path.join(path, 'DogMoveData.csv'),
                       usecols=
                       ['DogID', 'ABack_x', 'ABack_y', 'ABack_z',
                        'ANeck_y', 'ANeck_x', 'ANeck_z', 'GBack_x',
                        'GBack_y', 'GBack_z', 'GNeck_x', 'GNeck_y',
                        'GNeck_z', 'GBack_x', 'GBack_y', 'GBack_z',
                        'GNeck_x', 'GNeck_y', 'GNeck_z', 'Behavior_1'])

movedata = movedata.sample(frac=1, random_state=42).reset_index(drop=True)
movedata = movedata[:200000].sample(frac=1, random_state=42).reset_index(drop=True)

#filtering the data to remove undefined behavior
filtered_movedata = movedata[movedata['Behavior_1'] != '<undefined>']

#printing the numbers of occurrences of behaviors
print(filtered_movedata.Behavior_1.value_counts())

#some behaviors have little occurrences
#we can drop them
filtered_movedata = filtered_movedata[filtered_movedata['Behavior_1'] != 'Bowing']
filtered_movedata = filtered_movedata[filtered_movedata['Behavior_1'] != 'Jumping']
filtered_movedata = filtered_movedata[filtered_movedata['Behavior_1'] != 'Galloping']
filtered_movedata = filtered_movedata[filtered_movedata['Behavior_1'] != 'Tugging']
filtered_movedata = filtered_movedata[filtered_movedata['Behavior_1'] != 'Synchronization']
filtered_movedata = filtered_movedata[filtered_movedata['Behavior_1'] != 'Extra_Synchronization']

#take a sample
filtered_movedata = filtered_movedata[:37500]

#printing the numbers of occurrences of updated behaviors
print(filtered_movedata.Behavior_1.value_counts())

#getting the list of occuring behaviors
behaviors = filtered_movedata['Behavior_1'].unique()

#getting the number of unique behaviors
nOutputs = len(behaviors)

#getting the inputs
X = filtered_movedata[['ABack_x', 'ABack_y', 'ABack_z',
 'ANeck_y', 'ANeck_x', 'ANeck_z', 'GBack_x',
 'GBack_y', 'GBack_z', 'GNeck_x', 'GNeck_y',
 'GNeck_z', 'GBack_x', 'GBack_y', 'GBack_z',
 'GNeck_x', 'GNeck_y', 'GNeck_z']]

#getting the labels
y = pd.get_dummies(filtered_movedata['Behavior_1'])

#splitting the data into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(len(X_train))

#building and training the model
model = Sequential([
    Dense(18, input_dim=X_train.shape[1], activation='relu'),
    Dense(100, activation='relu'),
    Dense(nOutputs, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train and store history
history = model.fit(X_train, y_train, epochs=10, batch_size=1, verbose=1, validation_data=(X_test, y_test))



from sklearn.metrics import classification_report

# Make predictions on the test data
y_pred_probs = model.predict(X_test)

# Convert predictions probabilities to class labels
y_pred = np.argmax(y_pred_probs, axis=1)

# Convert one-hot encoded y_test to class labels
y_true = np.argmax(y_test.values, axis=1)

# Get the list of behavior names for target_names
behavior_names = y_test.columns.tolist()

# Generate and print the classification report
print(classification_report(y_true, y_pred, target_names=behavior_names))

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    classification_report, confusion_matrix, accuracy_score,
    precision_score, recall_score, f1_score, mean_squared_error
)

# === 1️⃣ Predict on Test Data ===
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)
y_true = np.argmax(y_test.values, axis=1)
behavior_names = y_test.columns.tolist()

# === 2️⃣ Classification Metrics ===
print("\n=== Classification Report ===")
print(classification_report(y_true, y_pred, target_names=behavior_names))

print("Accuracy:", accuracy_score(y_true, y_pred))
print("Precision (macro):", precision_score(y_true, y_pred, average='macro'))
print("Recall (macro):", recall_score(y_true, y_pred, average='macro'))
print("F1-Score (macro):", f1_score(y_true, y_pred, average='macro'))

# === 3️⃣ Confusion Matrix + Heatmap ===
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=behavior_names, yticklabels=behavior_names)
plt.title("Confusion Matrix Heatmap")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# === 4️⃣ Root Mean Square Error (RMS) ===
rms = np.sqrt(mean_squared_error(y_test, y_pred_probs))
print("RMS Error:", rms)

plt.figure(figsize=(12, 5))

# Accuracy Graph
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy Over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

# Loss Graph
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss Over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

from sklearn.ensemble import RandomForestClassifier

# Convert one-hot encoded labels back to integers
y_train_rf = np.argmax(y_train.values, axis=1)
y_test_rf = np.argmax(y_test.values, axis=1)

# Initialize and train the Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=20,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train_rf)

print("✅ Random Forest training complete.")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    classification_report, confusion_matrix, accuracy_score,
    precision_score, recall_score, f1_score, mean_squared_error
)

# === 1️⃣ Predictions ===
y_pred_rf = rf_model.predict(X_test)
y_pred_rf_proba = rf_model.predict_proba(X_test)
behavior_names = y_test.columns.tolist()

# === 2️⃣ Classification Metrics ===
print("\n=== Random Forest Classification Report ===")
print(classification_report(y_test_rf, y_pred_rf, target_names=behavior_names))

print("Accuracy:", accuracy_score(y_test_rf, y_pred_rf))
print("Precision (macro):", precision_score(y_test_rf, y_pred_rf, average='macro'))
print("Recall (macro):", recall_score(y_test_rf, y_pred_rf, average='macro'))
print("F1-Score (macro):", f1_score(y_test_rf, y_pred_rf, average='macro'))

# === 3️⃣ Confusion Matrix + Heatmap ===
cm = confusion_matrix(y_test_rf, y_pred_rf)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt="d", cmap="Greens",
            xticklabels=behavior_names, yticklabels=behavior_names)
plt.title("Random Forest Confusion Matrix Heatmap")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# === 4️⃣ Root Mean Square Error (RMS) ===
# y_pred_rf_proba has shape (n_samples, n_classes)
rms_rf = np.sqrt(mean_squared_error(y_test.values, y_pred_rf_proba))
print("RMS Error:", rms_rf)

